# -*- coding: utf-8 -*-
"""titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1coGMaOufOTDqfKiTBuuYm2vvOcz1VaMa
"""

#Importing important libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
import random

#Loading datasets
df=pd.read_csv("/content/titanic (1).csv",index_col=0)
df.isna()

#Creating Copies
df1=df.copy()

#Finding sum of missing values
df.isna().sum()

#Handling the missing values
#Finding the mean of Age variable
df['Age'].mean()

#Imputing missing values in Age column
df['Age'].fillna(df['Age'].mean(),inplace=True)

df.isna().sum()

#Finding the number of Categorical value
df['Cabin'].value_counts()

#Finding the mode of Categorical values
modes=df['Cabin'].mode()

if len(modes)>1:
  chosen_mode=random.choice(modes)
else:
  chosen_mode=modes[0]

#Imputing the missing values in Cabin column
df['Cabin'].fillna(chosen_mode,inplace=True)

df.isna().sum()

#Finding the number of Categorical values
df['Embarked'].value_counts()

df['Embarked'].value_counts().index[0]

#Imputing the missing values in Embarked Column
df['Embarked'].fillna(df['Embarked'].value_counts().index[0],inplace=True)

df.isna().sum()

#Data Visualisation
#Scatter plot of the dataset
sns.lmplot(x='Age',y='Fare',data=df, fit_reg=False,hue='Survived',legend=True,palette="Set1")
plt.title("Scatter plot of Age vs Fare of the Passengers")
plt.show()

#Histogram of the datasets
sns.displot(df['Fare'],kde=False,bins=5)
plt.hist(df['Fare'],color='maroon',edgecolor='green',bins=5)
plt.title("Histogram of Fare")
plt.show()

#Barplot of dataset
sns.countplot(x=df['Pclass'],data=df,hue='Embarked')
plt.title("Barplot of Pcalss")
plt.show()

#Boxplot of Dataset
sns.boxplot(x='Pclass',y='Age',data=df,hue='Survived',legend=True,palette="Set2")
plt.title("Boxplot of Pclass vs Age")
plt.show()

#Data Exploration
pd.crosstab(index=df['Survived'],columns=df['Embarked'],dropna=True)

#Two-Way Table-Joint Probability
pd.crosstab(index=df['Name'],columns=df['Cabin'],normalize=True,dropna=True)

#Two-Way-table-Marginal probability
pd.crosstab(index=df['Embarked'],columns=df['Ticket'],normalize=True,margins=True,dropna=True)

sns.barplot(x='Pclass',y='Age',data=df)

from scipy import constants

print(constants.pi)

print(constants.Boltzmann)